#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

#-------------------------------------------
# Configure the system to rely on slapd 
# for account and password management
#-------------------------------------------
{
    my @events = qw(
        bootstrap-console-save
        nethserver-directory-update
    );

    templates2events($_ , @events) foreach(qw(
	/etc/nsswitch.conf
	/etc/openldap/slapd.pem
	/etc/sysconfig/ldap
	/etc/openldap/ldap.conf
	/etc/libuser.conf
	/etc/pam_ldap.conf
	/etc/nslcd.conf
	/etc/pam.d/system-auth-nh
    ));
    
    event_link('initialize-default-databases', 'nethserver-directory-update', '00');
    event_link('nethserver-directory-conf', $_, '50') foreach(@events);
    event_link('nethserver-directory-dit-setup', $_, '51') foreach(@events);
    safe_symlink("restart", "root/etc/e-smith/events/$_/services2adjust/nslcd") foreach(@events);

    # Changes to the organization contacts are propagated into LDAP:
    event_link('nethserver-directory-dit-setup', 'nethserver-base-save', '50');
}
