#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);
use File::Path;

# slapd PKI certificate
my @certificates = (qw(
                /etc/pki/tls/certs/slapd.pem
));


#-------------------------------------------
# Configure the system to rely on slapd 
# for account and password management
#-------------------------------------------

event_templates('nethserver-directory-update', qw(
    /etc/openldap/ldap.conf
    /etc/libuser.conf
    /etc/sudoers
    /etc/sysconfig/slapd
), @certificates);

event_actions('nethserver-directory-update', qw(
	      initialize-default-databases               00
	      nethserver-directory-conf                  10
	      nethserver-directory-dit-setup             11
              nethserver-directory-fixconfig             12
              nethserver-directory-tlspolicy             20
	      nethserver-directory-createadmins          50
	      nethserver-directory-password-policy       60
	      nethserver-directory-sssd                  90
));

event_services('nethserver-directory-update', qw(
     rsyslog restart
));

# Synchronize LDAP database and user password aging on user
# modify event
event_actions($_, qw(
    nethserver-directory-user-modify     25
)) foreach(qw(
    user-modify
));

# Update user settings when password policy changes:
event_actions('password-policy-update',
	      'nethserver-directory-password-policy' => '30');


#--------------------------------------------------
# password-modify event
#--------------------------------------------------
event_actions('password-modify', qw(
              nethserver-directory-password-set 30
              nethserver-directory-user-unlock 40
));

#--------------------------------------------------
# actions for user-create event
#--------------------------------------------------
event_actions('user-create', qw(
    nethserver-directory-user-create 04
));

#--------------------------------------------------
# actions for user-delete event
#--------------------------------------------------
event_actions('user-delete', qw(
	      nethserver-directory-user-delete 70
	      nethserver-directory-user-delete-groups 80
));

#--------------------------------------------------
# actions for user-lock event
#--------------------------------------------------
event_actions('user-lock', qw(
              nethserver-directory-user-lock 15
));


#--------------------------------------------------
# actions for user-lock event
#--------------------------------------------------
event_actions('user-unlock', qw(
              nethserver-directory-user-unlock 15
));


#--------------------------------------------------
# actions for group-create event
#--------------------------------------------------
event_actions('group-create', qw(
	      nethserver-directory-group-create 04
	      nethserver-directory-group-modify 20
));


#--------------------------------------------------
# actions for group-delete event
#--------------------------------------------------
event_actions('group-delete', qw(
              nethserver-directory-group-delete 15
));


#--------------------------------------------------
# actions for group-modify event
#--------------------------------------------------
event_actions('group-modify', qw(
              nethserver-directory-group-modify 15
));



#
# certificate-update event
#
event_templates('certificate-update', @certificates);
event_services('certificate-update', qw(
    slapd restart
));


#
# migration-import event (refs #1655)
#
event_actions('migration-import', qw(
    nethserver-directory-migrate 20
));


#
# hostname-modify event
#
event_actions('hostname-modify', qw(
    nethserver-directory-conf   20
));
event_services('hostname-modify', qw(
    slapd restart
));

#
# actions for pre-backup-config event
#
event_actions('pre-backup-config', qw(
    nethserver-directory-dump-ldap   20
));


#
# actions for post-restore-config event
#
event_actions('post-restore-config', qw(
    nethserver-directory-restore-ldap   20
    nethserver-directory-clean-accountsdb 65
));

event_templates('post-restore-config', qw(
    /etc/pki/tls/certs/slapd.pem
));


#
# Event organization-save
#
event_actions('organization-save', qw(
    nethserver-directory-organization-modify 30
));

#
# Event nethserver-directory-ns6upgrade
#
event_actions('nethserver-directory-ns6upgrade', qw(
    nethserver-directory-fixldapsam 20
    nethserver-directory-ns6upgrade 30
));

#
# tls-policy-save event
#
event_actions('tls-policy-save', qw(
    nethserver-directory-tlspolicy 50
));
