#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

#-------------------------------------------
# Configure the system to rely on slapd 
# for account and password management
#-------------------------------------------
{

    event_templates('nethserver-directory-update', qw(
	/etc/nsswitch.conf
	/etc/sysconfig/ldap
	/etc/openldap/ldap.conf
	/etc/libuser.conf
	/etc/pam_ldap.conf
	/etc/nslcd.conf
	/etc/pam.d/system-auth-nh
    ));

    event_actions('nethserver-directory-update',
		  'initialize-default-databases' => '00',
		  'firewall-adjust' => '20',
		  'runlevel-adjust' => '20',
		  'nethserver-directory-conf' => '30',
		  'nethserver-directory-dit-setup' => '31',
		  'nethserver-directory-password-policy' => '40');

    # Changes to the organization contacts are propagated into LDAP:
    event_actions('nethserver-base-save',
		  'nethserver-directory-dit-setup' => '50');

    # Synchronize LDAP database and user password aging on user
    # create/modify event
    event_actions($_, 
		  'nethserver-directory-user-modify' => '25',
		  'nethserver-directory-password-policy' => '40' ) foreach(qw(
        user-create 
        user-modify
    ));
}
