#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use JSON;
use esmith::ConfigDB;
use NethServer::Directory;

my $db = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $nsDirectory = NethServer::Directory->new() || die('Could not access LDAP Directory');

my %groups;

my $domain = $db->get_value('DomainName');

my @entries = $nsDirectory->search(
    base => 'ou=Groups,dc=directory,dc=nh',
    filter => '(objectClass=posixGroup)',
    scope => 'one',
)->entries;

foreach  my $entry ( @entries ) {
    my $name = $entry->get_value('cn');
    my @members = map { $_.'@'.$domain } $entry->get_value('memberUid');

    $groups{$name.'@'.$domain}{'members'} = \@members;
}

print to_json(\%groups);

exit 0;
