#!/usr/bin/perl

use NethServer::Directory;
use NethServer::Directory::LDAP;
use esmith::ConfigDB;

my $ldap = NethServer::Directory::LDAP->new;
my $configDb = esmith::ConfigDB->open_ro();
my %OrganizationContact = $configDb->get('OrganizationContact')->props or {'Company' => 'Not Set'};
my $internalSuffix = NethServer::Directory::getInternalSuffix();

my @entries = (
    [ $internalSuffix,
      merge => [
	  objectClass => ['top', 'dcObject', 'organization'],
	  dc => 'directory',
	  o => $OrganizationContact{Company},
      ] ],    
    [ "ou=People,$internalSuffix",
      merge => [
	  objectClass => ['top', 'organizationalUnit'],
	  ou => 'People',
      ] ],
    [ "ou=Group,$internalSuffix",
      merge => [
	  objectClass => ['top', 'organizationalUnit'],
	  ou => 'Group',
      ] ],
    [ "ou=Computers,$internalSuffix",
      merge => [
	  objectClass => ['top', 'organizationalUnit'],
	  ou => 'Computers',
      ] ],

    #
    # authentication services accounts (replace with SASL whenever possible):
    #

    [ "cn=libuser,$internalSuffix",
      merge => [
	  objectClass => ['device', 'simpleSecurityObject'],
	  cn => 'libuser',
	  userPassword => NethServer::Directory::getUserPassword('libuser', 1, $ldap)
      ] ],
    [ "cn=pam,$internalSuffix",
      merge => [
	  objectClass => ['device', 'simpleSecurityObject'],
	  cn => 'pam',
	  userPassword => NethServer::Directory::getUserPassword('pam', 1, $ldap)
      ] ],
    );

my $exitCode = 0;

foreach(@entries) {
    my $method = @{$_}[1];
    my $message = $ldap->$method(@{$_});
    if($message->is_error) {
	warn 'Error modifying `' . @{$_}[0] . '`: ' . join(" ", $message->code, $message->error_name());
	$exitCode ++;
    }
}

exit($exitCode);
