#!/usr/bin/perl

use NethServer::Directory;
use esmith::ConfigDB;
use esmith::util;
use Net::LDAP;

my $configDb = esmith::ConfigDB->open_ro();

my $CertificateFile = "/etc/openldap/slapd.pem";
my $DomainName = $configDb->get_value('DomainName') || 'locahost.localdomain';
my $NslcdUid = getpwnam('nslcd');
my $LdapInternalSuffix = 'dc=directory,dc=nh';
my $LdapDomainSuffix = esmith::util::ldapBase($DomainName);

#
# Ensure slapd is running
#
qx(service slapd status >/dev/null);
if ( $? != 0 ) {
    qx(service slapd start);
    sleep 1;
}

#
# Connect to LDAP server
#
my $ldap = NethServer::Directory::bindLdap;

#
# Load the rwm overlay, if missing
#
my $RewriterModule = `rpm -ql openldap-servers | grep 'rwm\.la\$'`;
chomp($RewriterModule);

my $olcModuleSearch = $ldap->search(
    base => 'cn=config',
    filter => "(&(cn=module{0})(olcModuleLoad={0}$RewriterModule))",
    attributes => ['olcModuleLoad']
    );

if ($olcModuleSearch->count() == 0) {
    my $ldapAddResponse = $ldap->add(
	'cn=module,cn=config',
	attrs => [
	    cn => 'module',
	    olcModuleLoad => $RewriterModule	
	]
    );
    if($ldapAddResponse->is_error) {
	warn "`$RewriterModule` rwm module load error";
    }
}


#
# Replace some global settings
#
my @configChangeList = (
    ['cn=config',
     replace => [
	olcPasswordCryptSaltFormat => '$6$%.86s',
	olcTLSCipherSuite => $CertificateFile,
	olcTLSCACertificateFile => $CertificateFile,
	olcTLSCertificateFile => $CertificateFile,
	olcTLSCertificateKeyFile => $CertificateFile,
	olcTLSVerifyClient => 'never'
    ]],
    ['olcDatabase={-1}frontend,cn=config',
     replace => [olcPasswordHash => '{CRYPT}']],
    ['olcDatabase={2}bdb,cn=config',
     replace => [
	 olcSuffix => $LdapInternalSuffix,
	 olcAccess => [
	     qq{to * by dn.regex="^gidNumber=[0-9]+\\+uidNumber=(0|$NslcdUid),cn=peercred,cn=external,cn=auth\$" manage by * break},
	     q{to attrs=userPassword by anonymous auth by * break},
	     q{to attrs=entry,@shadowAccount,@posixAccount,@account  by anonymous read}
	 ]
     ]]
    );

foreach(@configChangeList) {
    my $ldapConfigResponse = $ldap->modify(@{$_});
    if($ldapConfigResponse->is_error) {
	warn 'error modifying ' . @{$_} . ' ' . $ldapConfigResponse->error ;
    }
}

#
# Enable relay overlay 
# see man slapd-relay, man slapo-rwm
#
my $olcRelaySearch = $ldap->search(
    base => 'cn=config',
    scope => 'one',
    filter => '(olcDatabase={0}relay)',
    attributes => ['olcSuffix']
    );

if($olcRelaySearch->count() == 0) {
    my $ldapAddRelayResponse = $ldap->add(
	'olcDatabase={0}relay,cn=config',
	attrs => [
	    objectClass => 'olcDatabaseConfig',
	    objectClass => 'olcRelayConfig',
	    objectClass => 'olcConfig',
	    olcDatabase => '{0}relay',
	    olcSuffix => $LdapDomainSuffix
	]
	);
    if(not $ldapAddRelayResponse->is_error) {	
	my $ldapAddOverlayResponse = $ldap->add(
	    'olcOverlay=rwm,' . $ldapAddResponse->dn(),
	    attrs => [
		objectClass => 'olcOverlayConfig',
		objectClass => 'olcRwmConfig',
		olcOverlay => 'rwm',
		olcRwmRewrite => 'rwm-suffixmassage "dc=directory,dc=nh"'
		]
	    );

	if(not $ldapAddOverlayResponse->is_error) {
	    warn 'Error adding rewrite module overlay: ' . $ldapAddOverlayReponse->error;
	}

    } else {
	warn 'Error adding relay database: ' . $ldapAddRelayReponse->error;
    }
}

$ldap->unbind;
