#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::Directory;

my $db = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $ldap = NethServer::Directory->new() || die "Could not connect NethServer LDAP backend";

my $errors = 0;
my $event = shift || die "Event name argument is missing\n";
my $groupName = shift || die "Group name argument is missing\n";
my @members = @ARGV;

# Handle users with and without domain part
my $account = undef;
if ($groupName =~ /@/) {
    $groupName = (split(/@/,$groupName))[0];
}

if($ldap->modify("cn=$groupName,ou=Groups,dc=directory,dc=nh", replace => [memberUid => \@members])->is_error()) {
    warn "[ERROR] failed to set members of group `$groupName`\n";
    $errors++;
}

exit ($errors == 0 ? 0 : 1);
