#!/usr/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

tlspolicy=$(/sbin/e-smith/config getprop tls policy)

if [[ -n ${tlspolicy} ]] && (( $tlspolicy >= 20180621 )); then
    ldapmodify -c -Y EXTERNAL &>/dev/null <<'EOF' || ((errors ++))
dn: cn=config
changetype: modify
replace: olcTLSCipherSuite
olcTLSCipherSuite: ECDHE:EDH:CAMELLIA:ECDH:RSA:ECDSA:!eNULL:!SSLv2:!RC4:!DES:!EXP:!SEED:!IDEA:!3DES:!ADH
-
replace: olcTLSProtocolMin
olcTLSProtocolMin: 3.2
EOF

else
    ldapmodify -c -Y EXTERNAL &>/dev/null <<'EOF'
dn: cn=config
changetype: modify
delete: olcTLSCipherSuite

dn: cn=config
changetype: modify
delete: olcTLSProtocolMin
EOF
    # If the error is "no such attribute" ignore it
    if (( $? != 0 && $? != 16 )); then
        ((errors ++))
    fi
fi

exit $errors
