#!/bin/bash

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

if ldapsearch -LLL -Y EXTERNAL '(|(objectClass=posixAccount)(objectClass=posixGroup))' dn 2>/dev/null | grep -q "^dn:" ; then
    # don't modify the LDAP tree if any account already exist
    exit 0
fi

echo "[NOTICE] creating administrative account"

EVENT=$1
USER=$(/sbin/e-smith/config getprop admins user)
GROUP=$(/sbin/e-smith/config getprop admins group)
ERRORS=0

/etc/e-smith/events/actions/nethserver-directory-user-create "$EVENT" "$USER" "$USER" "" || (( ERRORS ++ ))
/etc/e-smith/events/actions/nethserver-directory-group-create "$EVENT" domadmins "$USER" || (( ERRORS ++ ))
/etc/e-smith/events/actions/nethserver-directory-group-modify "$EVENT" domadmins "$USER" || (( ERRORS ++ ))

if [[ "$GROUP" != "domadmins" ]]; then
    ldapmodrdn -Y EXTERNAL 'cn=domadmins,ou=Groups,dc=directory,dc=nh' "cn=$GROUP" || (( ERRORS ++ ))
    ldapmodify -Y EXTERNAL <<EOF
dn: cn=$GROUP,ou=Groups,dc=directory,dc=nh
changetype: modify
replace: cn
cn: $GROUP
EOF
fi

ldapmodify -Y EXTERNAL <<EOF
dn: olcDatabase={2}hdb,cn=config
changetype: modify
replace: olcRootDN
olcRootDN: uid=${USER},ou=People,dc=directory,dc=nh
EOF

[[ $? == 0 ]] || (( ERRORS ++ ))

exit $ERRORS

