#!/bin/bash

# Check if SSSD is already configured for OpenLDAP
provider=$(/sbin/e-smith/config getprop sssd Provider)

if [ "$provider" == "none" ]; then # first install
    authconfig --enablesssdauth --enablemkhomedir --update
    /sbin/e-smith/config setprop sssd Provider ldap status enabled LdapURI ldap://127.0.0.1
    exec /sbin/e-smith/signal-event nethserver-sssd-save
fi
