#!/usr/bin/perl

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use NethServer::Directory;
use NethServer::Directory::LDAP;
use esmith::ConfigDB;

my $ldap = NethServer::Directory::LDAP->new;
my $configDb = esmith::ConfigDB->open_ro();
my %OrganizationContact = $configDb->get('OrganizationContact')->props or {'Company' => 'Not Set'};
my $internalSuffix = NethServer::Directory::getInternalSuffix();

my $exitCode = 0;

my $message = $ldap->merge($internalSuffix, attrs => [ o => $OrganizationContact{Company} ]);
if($message->is_error) {
    warn 'Error modifying `' . $internalSuffix . '`: ' . join(" ", $message->code, $message->error_name());
    $exitCode ++;
}

exit($exitCode);
