#!/usr/bin/perl

#
# NethServer Directory
#
# Update user(s) chage informations according to the current password
# policy.
#
# If the userName argument is missing, all known user accounts are
# considered.
#
# Copyright (C) 2012 Nethesis srl
#
# --- 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License or more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#

use strict;
use esmith::AccountsDB;

my $event = shift;
my $userName = shift;
my @users;
my $accountsDb = esmith::AccountsDB->open();

my $errors = 0;

if($userName) {
    @users = ($userName);
} else {
    @users = map { $_->key } $accountsDb->users();   
}

my %conf = ();

my $policy = esmith::ConfigDB->open_ro()->get('passwordstrength');
if($policy) {
    %conf = $policy->props();
} else {
    die "No passwordstrength configuration found!\n";
}

foreach $userName (@users) {

    my $record = $accountsDb->get($userName);

    if( ! $record || $record->prop('type') ne 'user') {
	warn "Invalid user account: `$userName`\n";
	$errors ++;
	next;
    }

    if($conf{'PassExpires'} ne 'no' && ($record->prop("PassExpires") || 'yes') ne 'no') {
        system("/usr/sbin/lchage",
            "-m", $conf{"MinPassAge"} || '0',
            "-M", $conf{"MaxPassAge"} || '180',
            "-W", $conf{"PassWarning"} || '7',
            $userName);
	if( $? != 0 ) {
	    warn "Error setting password age infos for user `$userName`\n";
	    $errors ++;	    
	}
    } else {
        system(qw(/usr/sbin/lchage -m 0 -M 99999 -W 7), $userName);
	if( $? != 0 ) {
	    warn "Error removing password age infos for user `$userName`\n";
	    $errors ++;	    
	}
    }

}

exit(($errors > 0) ? 1 : 0);


