#!/bin/bash 

# NethServer
#
# Create the default slapd TLS certificate. Refs #1491
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

CMDDB="/sbin/e-smith/db"

HOSTNAME=`hostname`
City=`$CMDDB configuration getprop OrganizationContact City`
Company=`$CMDDB configuration getprop OrganizationContact Company`

#
# This script is part of openldap-servers
# openldap-servers-2.4.23-20.el6.x86_64
#

# generate sample TLS certificates
if [ ! -f /etc/pki/tls/certs/slapd.pem ] ; then
pushd /etc/pki/tls/certs > /dev/null 2>&1
umask 077
cat << EOF | make slapd.pem > /dev/null 2>&1
--
SomeState
${City:=SomeCity}
${Company:=SomeOrganization}
SomeOrganizationalUnit
${HOSTNAME:=localhost.localdomain}
root@${HOSTNAME:=localhost.localdomain}
EOF
chown root:ldap slapd.pem
chmod 640 slapd.pem
popd &>/dev/null
fi

