#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#


use strict;

my $event = shift;
my $userName = shift;

if( ! $userName ) {
    warn("[ERROR] Missing username argument");
    exit(1);
} elsif ( $userName !~ /\@/ ) {
    warn("[WARNING] Skipping user $userName, it doesn't belong to a domain.\n");
    exit(0);
}

$userName = (split(/@/,$userName))[0];

# Do not unlock users without password
my $currentPassword = qx(/usr/bin/ldapsearch -o ldif-wrap=no -LLL -Y EXTERNAL '(uid=$userName)' userPassword 2>/dev/null | /usr/bin/grep ^userPassword);
chomp $currentPassword;

# e0NSWVBUfSEh is base64 form of empty password: {CRYPT}!!
if ($currentPassword eq 'userPassword:: e0NSWVBUfSEh') {
    print("[NOTICE] Skipping unlock for user $userName\n");
    exit(0);
}

system("/usr/sbin/lusermod", "-U", $userName) == 0
        or die "[ERROR] could not unlock account $userName\n";

exit 0;
