#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;

my $event = shift;
my $userName = shift;;

#------------------------------------------------------------
# Delete the Unix account.
#------------------------------------------------------------

die "Username argument missing." unless defined ($userName);

# Handle users with and without domain part
if ($userName =~ /@/) {
    $userName = (split(/@/,$userName))[0];
}

system('/usr/sbin/luserdel', $userName) == 0 ||
    die "Failed to delete account $userName: $!";
exit (0);
