#!/usr/bin/perl -w

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# Copyright (C) 1999, 2000 e-smith, inc.
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use NethServer::Database::Passwd;
use esmith::ConfigDB;

my $event = shift;
my $userName = shift;
my $name = shift || '';
my $shell = shift || '/usr/libexec/openssh/sftp-server';

my $db = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $passwd = esmith::db->open("NethServer::Database::Passwd") || die("Could not open Passwd DB");
my $contactRecord = $db->get('OrganizationContact');


if( ! $userName ) {
    warn("[ERROR] Missing username argument");
    exit(1);
}

if( ! $contactRecord ) {
    warn("[ERROR] Could not open OrganizationContact record");
    exit(1);
}

# Handle users with and without domain part
my $account = undef;
if ($userName =~ /@/) {
    $account = $passwd->get($userName);
    $userName = (split(/@/,$userName))[0];
} else {
    my $domain = $db->get_value('DomainName');
    $account = $passwd->get($userName.'@'.$domain);
}
if( ! $account) {
    die "[ERROR] Account `$userName` not found.\n";
}

$name =~ s/^\s+//g;
$name =~ s/\s+$//g;

my $gecos = $name;
# gecos must be 7bit ASCII/ldap IA5String. Refs #911
$gecos =~ s/[^\x20-\x7F]//g;

system('/usr/sbin/lusermod',
   '--commonname=' . $name,
   '--shell=' . $shell,
   '--gecos=' . $gecos,
   $userName);

if($? != 0) {
    die("[ERROR] Failed to modify user `$userName` fields!\n");
}


exit(0);
