#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Drop group records in AccountsDB. Since ns7 they are no longer used.

use strict;
use esmith::AccountsDB;

my $adb = esmith::AccountsDB->open() || die ("Could not open AccountsDB");
my $domain = `hostname -d`;
chomp $domain;

foreach ($adb->groups()) {
    $_->delete();
}

foreach my $user ($adb->users()) {
    next if ($user->key =~ /@/);

    my $dst_user_key = $user->key."@".$domain;
    my %props = $user->props;
    foreach my $key (keys %props) {
        if (grep(/City|Company|Department|FirstName|LastName|PassExpires|PhoneNumber|Shell|Street|Uid|__state/,$key)) {
            delete $props{$key};
        }
    }

    $user->delete();

    my $account_record = $adb->get($dst_user_key);
    if (defined($account_record)) {
        $account_record->merge_props(%props);
    } else {
        $adb->new_record($dst_user_key, \%props);
    }
}
