#!/usr/bin/perl

use NethServer::Directory;
use NethServer::Directory::LDAP;
use esmith::ConfigDB;

my $ldap = NethServer::Directory::LDAP->new;
my $configDb = esmith::ConfigDB->open_ro();
my %OrganizationContact = $configDb->get('OrganizationContact')->props or {'Company' => 'Not Set'};
my $internalSuffix = NethServer::Directory::getInternalSuffix();

my $exitCode = 0;

my $message = $ldap->merge($internalSuffix, attrs => [ o => $OrganizationContact{Company} ]);
if($message->is_error) {
    warn 'Error modifying `' . $internalSuffix . '`: ' . join(" ", $message->code, $message->error_name());
    $exitCode ++;
}

exit($exitCode);
