#!/usr/bin/perl -w

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

package esmith;

use strict;
use Errno;

my $event = $ARGV [0];
my $groupName = $ARGV [1] or die "Groupname argument missing.";

# Handle groups with and without domain part
if ($groupName =~ /@/) {
    $groupName = (split(/@/,$groupName))[0];
}

system("/usr/sbin/lgroupdel", $groupName) == 0
    or die "Failed to delete group $groupName.\n";

exit (0);
