#!/usr/bin/perl -w

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::Directory;
use NethServer::Database::Passwd;
use File::Path;

my $conf = esmith::ConfigDB->open_ro() || die("Could not open Config DB");
my $passwd = esmith::db->open("NethServer::Database::Passwd") || die("Could not open Passwd DB");
my $homeDirPrefix = '/var/lib/nethserver/home/';

my $errors = 0;

my $event = shift;
my $userName = shift;
my $name = shift || '';
my $shell = shift || '/usr/libexec/openssh/sftp-server';

if( ! defined ($userName)) {
    die "Username argument missing\n";
}

if( ! -x $shell) {
    warn "Given shell `$shell` is not executable";
    $shell = '/bin/false';
}

# Create the home directory prefix if still does not exists
if( ! -d $homeDirPrefix) {
    File::Path::make_path($homeDirPrefix);
}

$name =~ s/^\s+//g;
$name =~ s/\s+$//g;

my $gecos = $name;
# gecos must be 7bit ASCII/ldap IA5String. Refs #911
$gecos =~ s/[^\x20-\x7F]//g;


# Now create the user account. `--surname` triggers inetOrgPerson
# schema in ldapEntry and is required for nethserver-directory to
# work.
system(
	"/usr/sbin/luseradd",
        '-g', 'locals',
        '-n',
        '--surname', $userName,
	'-d', $homeDirPrefix . $userName,
	"-k", "/etc/skel/",
	"-s", $shell,
	'--commonname=' . $name ,
   	'--gecos=' . $gecos,
	$userName
    ) == 0 or die "Failed to create user account `$userName`.\n";


# Set initial permissions on user's root directory.
chmod 0700, $homeDirPrefix . $userName;

my $ldap = NethServer::Directory->new();
my $domain = $conf->get_value('DomainName');
if($ldap->modify("uid=$userName,ou=People,dc=directory,dc=nh", replace => [mail => ($userName.'@'.$domain)])->is_error()) {
    warn "[ERROR] failed to set mail field for user '$userName'\n";
}

exit ($errors == 0 ? 0 : 1);
