#!/bin/bash

#
# NethServer
#
# Copyright (C) 2012 Nethesis srl
#

if [ $# -ge 3 ]; then
   EVENT=$1
   USER=$2
   FILE=$3
   /usr/bin/shred -u $FILE 2> /dev/null 
else
   echo "Not enough arguments"
   exit 1
fi

