#!/usr/bin/perl

#
# NethServer
#
# Copyright (C) 2012 - Nethesis srl
# 

use strict;
use esmith::ConfigDB;
use Crypt::Cracklib;


my $objectType = shift;
my $password = shift;
my $reason;

if( ! defined $objectType ) {
    die "Missing objectType argument";
}

if( ! defined $password ) {
    die "Missing password argument";
}

my $configDb = esmith::ConfigDB->open_ro();
my $strength = $configDb->get_prop('passwordstrength', $objectType);

if ( ! defined $strength ) {
    # skip to end..

} elsif( length($password) < 7 ) {
    # too_short
    exit 3;

} elsif( $strength eq 'none' ) {
    exit 0;

} elsif( $strength eq 'strong') {
    exit 5 if (not $password =~ /\d/); #missing digit
    exit 6 if ($password !~ /[A-Z]/); #missing capital
    exit 7 if ($password !~ /[a-z]/); #missing lowercase
    exit 8 if ($password !~ /\W|_/); #missing symbol

    $reason = Crypt::Cracklib::fascist_check($password);
    if($reason ne 'ok') {
	print $reason . "\n";
	exit 4; #system error
    }

    exit 0;   
} 

die "Invalid password strength for object " . $objectType;

